import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <div className="header  text-white font-semibold flex bg-blue-600 px-4 justify-between items-center p-4 text-2xl">
          <div className="logo">
           codex
          </div>
          <div className="navigation flex gap-4">
            <div className="posts">
              <Link href='/posts'>Posts</Link>
            </div>
            <div className="details">
              <Link href='/details'>Details</Link>
          </div>
        </div>
          <div className="user">
            <Avatar>
        <AvatarImage src="https://play-lh.googleusercontent.com/t7VjTonSiOlxVgQlRQ5hLy-sIiC6KHY_zhAu4UYv9IJVzDt0uEXCdU1xd1kO1FWdNkc=w240-h480-rw" alt="@shadcn" />
        <AvatarFallback></AvatarFallback>
      </Avatar>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
